apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alpine-server-deployment
  name: alpine-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine-server-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alpine-server-deployment
    spec:
      containers:
      - image: mhejrati20/aut:alpine-server 
        name: alpine-server
        resources: {}
        volumeMounts:
        - mountPath: config.yml
          subPath: config.yml
          name: config-map
        ports:
          - containerPort: 8765
      volumes:
      - name: config-map
        configMap:
          name: server-config
status: {}
